services:
  - type: web
    name: discord-bot-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    branch: main
    rootDir: backend
    envVars:
      - key: RENDER_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: your-postgres
          property: connectionString

databases:
  - name: your-postgres
    plan: free
